@host = https://opmapi.azurewebsites.net
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyIiwiaWF0IjoxNjY4ODY5OTQ1LCJleHAiOjE2Njg4NzAwNjV9.FhGWNG2e-9R8ev4HWhqQW7FdWsPySxZBReF8a73pPEQ

GET {{host}}/milestones

###
GET {{host}}/projects/1/milestones/1
Authorization:Bearer {{token}}

###
POST {{host}}/projects/1/milestones
Content-Type: application/json
Authorization:Bearer {{token}}

{
  "name": "TestVersion1",
  "description": "Description",
  "deadline": "2022-2-2"
}

###
PUT {{host}}/milestones/1
Content-Type: application/json
Authorization:Bearer {{token}}

{
  "name": "ModifiedVersion",
  "description": "Asd123",
  "deadline": "1001-10-10",
  "status": "Done",
  "taskIds": [1]
}

###
DELETE {{host}}/milestones/1
Authorization:Bearer {{token}}


###
POST {{host}}/resettestdata