@host = http://localhost:5000

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyIiwiaWF0IjoxNjY5MDY1ODQ2LCJleHAiOjE2NjkwNjU5NjZ9.Z_ifQqK9FyN5MT4XAkw9p76AB7UZD_A5Ws3IMFJqiEg

GET {{host}}/projects/2/milestones
Authorization:Bearer {{token}}

###
GET {{host}}/projects/1/milestones/1
Authorization:Bearer {{token}}

###
POST {{host}}/projects/1/milestones
Content-Type: application/json
Authorization:Bearer {{token}}

{
  "name": "TestVersion1",
  "description": "Description",
  "deadline": "2022-2-2"
}

###
PUT {{host}}/projects/1/milestones/2
Content-Type: application/json
Authorization:Bearer {{token}}

{
  "name": "ModifiedVersion",
  "description": "Asd123",
  "deadline": "1001-10-10",
  "status": "Done",
  "taskIds": [1]
}

###
DELETE {{host}}/projects/2/milestones/1
Authorization:Bearer {{token}}