@host = http://localhost:5000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyIiwiaWF0IjoxNjY5MTQ5NTc4LCJleHAiOjE2NjkxNDk2OTh9.BHLKnanMW37Q4OhPr9le1ukIpKndqhjcVV5WlJE1jzQ

GET {{host}}/projects
Authorization: Bearer {{token}}

###
GET {{host}}/projects/1
Authorization: Bearer {{token}}

###
DELETE {{host}}/projects/1
Authorization: Bearer {{token}}

###
POST {{host}}/projects
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Test project 2",
  "description": "description",
  "startDate": "2022-11-22",
  "endDate": null,
  "estimatedTime": 123
}

###
PUT {{host}}/projects/2
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Modified",
  "description": "Description",
  "startDate": "2012-01-01",
  "endDate": "2022-02-02",
  "estimatedTime": 232
}