# @host = https://opmapi2.azurewebsites.net
@host = http://localhost:5000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY2OTQ2Njk3NiwiZXhwIjoxNjY5NDY3MDk2fQ.ZYNuGkz6KWFpETJ-eJjqFMa7JK-8HImA04l7aB3_3x0

#Get projects
GET {{host}}/projects?pageNumber=1
Authorization: Bearer {{token}}

###

#Get project by id
GET {{host}}/projects/2
Authorization: Bearer {{token}}

###

#Delete project by id
DELETE {{host}}/projects/2
Authorization: Bearer {{token}}

###

#Create new project
POST {{host}}/projects
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Test project 2",
  "description": "description",
  "startDate": "2022-11-22",
  "endDate": null,
  "status": "In Progress",
  "estimatedTime": 123,
  "managerId": 1,
  "memberIds": []
}

###

#Update project
PUT {{host}}/projects/2
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Modified",
  "description": "Description",
  "startDate": "2012-01-01",
  "endDate": "2020-03-21",
  "status": "Stopped",
  "estimatedTime": 232
}