# @host = https://opmapi2.azurewebsites.net
@host = http://localhost:5000

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY2OTQ2ODU0MywiZXhwIjoxNjY5NDc1NzQzfQ.GoxZImIPQHNsGgN34MRkih4Ank6AoYLSW6yn-lmiCf0

#Get tasks
GET {{host}}/projects/1/tasks?pageNumber=1
Authorization:Bearer {{token}}

###

#Get task by id
GET {{host}}/projects/1/tasks/3
Authorization:Bearer {{token}}

###

#Create task
POST {{host}}/projects/1/tasks
Content-Type: application/json
Authorization:Bearer {{token}}

{
  "name": "Test task #2",
  "description": "description",
  "deadline": "2022-01-11",
  "status": "Done",
  "assigneeIds": [1, 2],
  "prerequisiteTaskIds: []"
}

###

#Update task
PUT {{host}}/projects/1/tasks/1
Content-Type: application/json
Authorization:Bearer {{token}}

{
  "name": "Modified",
  "description": "description",
  "status": "Done",
  "deadline": "1999-01-10",
  "assigneeIds": [1]
}

###

#Archive task
PUT {{host}}/projects/2/tasks/2/archive
Content-Type: application/json
Authorization:Bearer {{token}}

{
  "archived": false
}
