# @host = https://opmapi.azurewebsites.net
@host = http://localhost:5000

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlhdCI6MTY2OTU2NDU2MSwiZXhwIjoxNjY5NTcxNzYxfQ.gsMkkcApf-UkEklPaC0vQHe639O95oU3yea7k7Y9pGA
#Get tasks
GET {{host}}/projects/1/tasks
Authorization:Bearer {{token}}

###

#Get task by id
GET {{host}}/projects/2/tasks/2
Authorization:Bearer {{token}}

###

#Create task
POST {{host}}/projects/1/tasks
Content-Type: application/json
Authorization:Bearer {{token}}

{
  "name": "Nem",
  "description": "description",
  "deadline": "2022-12-25",
  "status": "Done",
  "prerequisiteTaskIds": [],
  "assigneeIds": [1]
}

###

#Update task
PUT {{host}}/projects/1/tasks/1
Content-Type: application/json
Authorization:Bearer {{token}}

{
  "name": "Modified",
  "description": "description",
  "status": "Done",
  "deadline": "1999-01-10",
  "assigneeIds": []
}

###

#Archive task
PUT {{host}}/projects/1/tasks/1/archive
Content-Type: application/json
Authorization:Bearer {{token}}

{
  "archived": true
}

###

#Get task stats
GET {{host}}/projects/1/tasks/stats
Authorization:Bearer {{token}}