# @host = https://opmapi.azurewebsites.net
@host = http://localhost:5000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY2OTU3MzE5OSwiZXhwIjoxNjY5NTgwMzk5fQ.Q9zwTNtdjaFkmK0vtEfz2ZOBPHYmCbrpD1oDdIBl1-Y

#Get users
GET {{host}}/users

###

#Login
POST {{host}}/user/login
Content-Type: application/json

# {
#   "username": "kengushi",
#   "password": "kengushi"
# }

{
  "username": "testuser",
  "password": "test123"
}

# {
#   "username": "asdasd",
#   "password": "asd"
# }

###

#Signup
POST {{host}}/user/signup
Content-Type: application/json

{
  "username": "asdasd",
  "fullname": "asd123",
  "email": "asd@example.com",
  "password": "asd"
}

###

#Logout
GET {{host}}/user/logout

###

#Refresh access token
GET {{host}}/refresh
Authorization: Bearer {{token}}

###

#Get current logged in user
GET {{host}}/user/current
Authorization: Bearer {{token}}

###

GET {{host}}/user/tasks
Authorization: Bearer {{token}}

###

#Reset all data and database
POST {{host}}/resettestdata