@host = http://localhost:5000
@token = 

GET {{host}}/users

###
POST {{host}}/user/signup
Content-Type: application/json

{
  "username": "testuser",
  "fullname": "Test User",
  "email": "testuser@example.com",
  "password": "asd123QWE"
}

###
GET {{host}}/user/login
Content-Type: application/json

{
  "username": "testuser",
  "password": "test123"
}

###
GET {{host}}/user/logout

###
GET {{host}}/refreshToken