@host = http://localhost:5000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyIiwiaWF0IjoxNjY5MjAwNjg5LCJleHAiOjE2NjkyMDA4MDl9.NYQ5ZVhZASkUQXZoFPclomDb7FZeBy4Uy2_wp-Wi5zc

#Get tasks
GET {{host}}/projects/2/tasks?pageNumber=3
Authorization:Bearer {{token}}

###

#Get task by id
GET {{host}}/projects/2/tasks/2
Authorization:Bearer {{token}}

###

#Create task
POST {{host}}/projects/2/tasks
Content-Type: application/json
Authorization:Bearer {{token}}

{
  "name": "Test task #2",
  "description": "description",
  "deadline": "2022-01-11",
  "status": "Done"
}

###

#Update task
PUT {{host}}/projects/2/tasks/3
Content-Type: application/json
Authorization:Bearer {{token}}

{
  "name": "Modified",
  "description": "description",
  "status": "Done",
  "deadline": "1999-01-10",
  "assigneeIds": [1],
  "prerequisiteTaskIds": [2]
}

###

#Archive task
PUT {{host}}/projects/2/tasks/2/archive
Content-Type: application/json
Authorization:Bearer {{token}}

{
  "archived": true
}
